/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucideAlertCircle: typeof import('~icons/lucide/alert-circle').default;
  const LucideAlertTriangle: typeof import('~icons/lucide/alert-triangle').default;
  const LucideAlignCenter: typeof import('~icons/lucide/align-center').default;
  const LucideAlignLeft: typeof import('~icons/lucide/align-left').default;
  const LucideAlignRight: typeof import('~icons/lucide/align-right').default;
  const LucideBold: typeof import('~icons/lucide/bold').default;
  const LucideBookUser: typeof import('~icons/lucide/book-user').default;
  const LucideCalendar: typeof import('~icons/lucide/calendar').default;
  const LucideCalendarPlus: typeof import('~icons/lucide/calendar-plus').default;
  const LucideCamera: typeof import('~icons/lucide/camera').default;
  const LucideCheck: typeof import('~icons/lucide/check').default;
  const LucideCheckCheck: typeof import('~icons/lucide/check-check').default;
  const LucideCheckCircle: typeof import('~icons/lucide/check-circle').default;
  const LucideChevronDown: typeof import('~icons/lucide/chevron-down').default;
  const LucideChevronLeft: typeof import('~icons/lucide/chevron-left').default;
  const LucideChevronRight: typeof import('~icons/lucide/chevron-right').default;
  const LucideChevronUp: typeof import('~icons/lucide/chevron-up').default;
  const LucideCircle: typeof import('~icons/lucide/circle').default;
  const LucideCircleCheck: typeof import('~icons/lucide/circle-check').default;
  const LucideClock: typeof import('~icons/lucide/clock').default;
  const LucideCode: typeof import('~icons/lucide/code').default;
  const LucideCopy: typeof import('~icons/lucide/copy').default;
  const LucideDownload: typeof import('~icons/lucide/download').default;
  const LucideImage: typeof import('~icons/lucide/image').default;
  const LucideImport: typeof import('~icons/lucide/import').default;
  const LucideInfo: typeof import('~icons/lucide/info').default;
  const LucideItalic: typeof import('~icons/lucide/italic').default;
  const LucideLink2: typeof import('~icons/lucide/link2').default;
  const LucideList: typeof import('~icons/lucide/list').default;
  const LucideListFilter: typeof import('~icons/lucide/list-filter').default;
  const LucideListOrdered: typeof import('~icons/lucide/list-ordered').default;
  const LucideLoader: typeof import('~icons/lucide/loader').default;
  const LucideLoader2: typeof import('~icons/lucide/loader2').default;
  const LucideLogOut: typeof import('~icons/lucide/log-out').default;
  const LucideMail: typeof import('~icons/lucide/mail').default;
  const LucideMaximize2: typeof import('~icons/lucide/maximize2').default;
  const LucideMenu: typeof import('~icons/lucide/menu').default;
  const LucideMessageSquare: typeof import('~icons/lucide/message-square').default;
  const LucideMinimize2: typeof import('~icons/lucide/minimize2').default;
  const LucideMinus: typeof import('~icons/lucide/minus').default;
  const LucideMoon: typeof import('~icons/lucide/moon').default;
  const LucideMoreHorizontal: typeof import('~icons/lucide/more-horizontal').default;
  const LucideMoreVertical: typeof import('~icons/lucide/more-vertical').default;
  const LucideOctagonX: typeof import('~icons/lucide/octagon-x').default;
  const LucidePaperclip: typeof import('~icons/lucide/paperclip').default;
  const LucidePencil: typeof import('~icons/lucide/pencil').default;
  const LucidePlus: typeof import('~icons/lucide/plus').default;
  const LucideQuote: typeof import('~icons/lucide/quote').default;
  const LucideRemoveFormatting: typeof import('~icons/lucide/remove-formatting').default;
  const LucideSave: typeof import('~icons/lucide/save').default;
  const LucideSearch: typeof import('~icons/lucide/search').default;
  const LucideSend: typeof import('~icons/lucide/send').default;
  const LucideSettings: typeof import('~icons/lucide/settings').default;
  const LucideSmile: typeof import('~icons/lucide/smile').default;
  const LucideStar: typeof import('~icons/lucide/star').default;
  const LucideTrash2: typeof import('~icons/lucide/trash2').default;
  const LucideTriangleAlert: typeof import('~icons/lucide/triangle-alert').default;
  const LucideUnderline: typeof import('~icons/lucide/underline').default;
  const LucideUpload: typeof import('~icons/lucide/upload').default;
  const LucideUser: typeof import('~icons/lucide/user').default;
  const LucideX: typeof import('~icons/lucide/x').default;
}
